### PR TITLE
Manual updates 20221031 gps only - issue repro

### PR DESCRIPTION
**Pull request by moljac**

### CODE REVIEW

**Comment by moljac** [comment]
error to investigate:

```
./generated/com.google.android.gms.play-services-location/obj/Release/monoandroid12.0/generated/src/Android.Gms.Location.IFusedLocationProviderClient.cs(9,24): 
error CS0260: 
Missing partial modifier on declaration of type 'FusedLocationProviderClient'; 
another partial declaration of this type exists 
[./generated/com.google.android.gms.play-services-location/com.google.android.gms.play-services-location.csproj]
```

**Comment by moljac** [comment]
error:

```
```

```
find \
    generated/com.google.android.gms.play-services-location/obj/Release/monoandroid12.0/ \
    -type f \
    -name "*.cs" \
    -exec grep -Hni "class FusedLocationProviderClient" {} \;
```

Seems like java `interface IName` generates `abstract class Name`, but we have `Additions/Name.cs` with `partial class Name`

in this case `Name = FusedLocationProviderClient`

```
generated/com.google.android.gms.play-services-location/obj/Release/monoandroid12.0//generated/src/Android.Gms.Location.IFusedLocationProviderClient.cs:9:	public abstract class FusedLocationProviderClient : Java.Lang.Object {
generated/com.google.android.gms.play-services-location/obj/Release/monoandroid12.0//generated/src/Android.Gms.Location.IFusedLocationProviderClient.cs:36:	public abstract class FusedLocationProviderClientConsts : FusedLocationProviderClient {
```

**Comment by moljac** [comment]
similar issue:

https://github.com/xamarin/AndroidX/pull/684/

**Comment by jpobst** [comment]
It looks like these types changed from being `class` in `20.0` to `interface` in `21.0`  😢 

`20.0`:
image

`21.0`:
image

I guess the best we can do is update `TaskExtensions` so that it matches.  I don't really know what effect(s) this may have on users.  This is not a change you would ever make in a .NET library where you are trying to maintain any semblance of backwards compatibility.  🤷‍♂️

**Pull request closed without merging**
