### PR TITLE
Change Play.Core binding transforms to fix inconsistency with native library

### PR DESCRIPTION
**Pull request by wcoder**
### Google Play Services Version (eg: 8.4.0):
Android Play Core 1.10.0

### Does this change any of the generated binding API's?
Yes

### Describe your contribution
More details in issue #483

### CODE REVIEW

**Comment by wcoder** [comment]
@moljac could you please share CI error?

**Comment by moljac** [comment]
signing failed.

```
##[error]Access denied. DevDiv Build Service (devdiv) needs Edit build quality permissions for vstfs:///Build/Build/4952561 in team project DevDiv to perform the action.
```

Why? Dunno.

**Comment by wcoder** [comment]
@moljac looks the same 😕

do you know anyone who can fix the pipelines?

**Comment by jpobst** [comment]
Weird, my PR earlier today did not have this failure: https://github.com/xamarin/GooglePlayServicesComponents/pull/494.

But I ran this step again on this one and it still fails.

I suspect we can just ignore it.  We should probably disable signing for anything other than a release tag, like we did on AndroidX: https://github.com/xamarin/AndroidX/pull/197/files.

**Comment by wcoder** [comment]
yes, it makes sense(

Is there any other way I can submit the PR with a possible fix, or can someone check this PR locally?

**Comment by wcoder** [comment]
@jonathanpeppers Maybe you can help us?

**Comment by wcoder** [comment]
@jamesmontemagno Could you please push activity for this PR?

As I can see, StoreReviewPlugin used a package to work around the same issue:
https://github.com/jamesmontemagno/StoreReviewPlugin/blob/98778f4c1c9240482f5b8f04abb70b602df21c88/src/StoreReview.Plugin/StoreReview.Plugin.csproj#L73

**Comment by dellis1972** [comment]
@wcoder it worked for me locally, can you rebase this PR on the latest `main` and we can see if we can get this in

**Comment by wcoder** [comment]
@dellis1972 thanks!

@moljac could you please review this PR?

**Review by moljac — APPROVED** [review]

**Review by jpobst — APPROVED** [review]

**Comment by wcoder** [comment]
@moljac 
Maybe you know when these changes will be available in NuGet?

**Pull request merged**
