### PR TITLE
Add *BuildAllDotNet samples to ensure we can build on 'net6.0-android'.

### PR DESCRIPTION
**Pull request by jpobst**
As part of CI, we build a projects called `*BuildAll.csproj` to ensure that our packages can be consumed.  We should have this same smoke test for .NET 6 packages and applications.  Add `*BuildAllDotNet.csproj` projects that will perform this test for .NET.

Note this does not currently build, as several package issues must be fixed first (highlighting the need for this test!).

edit by moljac:

basically - ported AndroidX PR: https://github.com/xamarin/AndroidX/pull/583

### Does this change any of the generated binding API's?

No - infrastructure changes.

### Describe your contribution

- refactored (split) net6 and classic samples into folders
  - samples split into `msbuild` and `dotnet build` builds
- added new samples (net6 MAUI)
  - net6 MAUI BuildAll (`BuildAllMauiApp`) and 
  - Xamarin Froms short style (`BuildAllXamarinForms`) currently investigating iOS build (Android OK)
- added nuget central package management for the net6 samples samples 
  - `Directory.Packages.props`, `PackageVersion`...

### CODE REVIEW

**Comment by moljac** [comment]
intermittent failures on CI

macosx:

```
========================================
tools-executive-order
========================================
Error: Bad IL format. The format of the file '/Users/runner/work/1/s/tools/Addins/runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple.4.3.0/runtimes/osx.10.10-x64/native/System.Security.Cryptography.Native.Apple.dylib' is invalid.
An error occurred when executing task 'tools-executive-order'.
Error: .NET CLI: Process returned an error (exit code 1).
##[error]PowerShell exited with code '1'.
```

windows:

```
Workload updates are available. Run `dotnet workload list` for more information.
An error occurred when executing task 'samples-dotnet'.
An error occurred when executing task 'samples'.
Error: Access to the path 'C:\a\_work\1\s\samples\packages-dotnet\xamarin.androidx.migration\1.0.10\buildTransitive\monoandroid120\Xamarin.AndroidX.Migration.BuildTasks.dll' is denied.
##[error]PowerShell exited with code '1'.

```

**Comment by jpobst** [comment]
As best I can tell, this does not run the majority of the new test suites.  I think the only new one it runs is `PlayBuildAll`: https://github.com/xamarin/GooglePlayServicesComponents/pull/639/files#diff-91fcb59c3dd53babb75b34f23269bb6972fae348be4ade7f9e1786d4cafae586.

None of the other suites are added to `BuildAll.sln` or `build.cake`, so they are not being run by CI.

`dotnet/BuildAllXamarinForms` is probably also unneeded, as XF does not run on .NET 6+.

**Comment by moljac** [comment]
after build.cake fixes:

```
output/samples-dotnet-dotnet-debug-BuildAllDotNet.binlog
output/samples-dotnet-dotnet-debug-BuildAllMauiApp.binlog
output/samples-dotnet-dotnet-debug-BuildAllXamarinForms.binlog
output/samples-dotnet-dotnet-release-BuildAllDotNet.binlog
output/samples-dotnet-dotnet-release-BuildAllMauiApp.binlog
output/samples-dotnet-dotnet-release-BuildAllXamarinForms.binlog
```

**Comment by moljac** [comment]
> As best I can tell, this does not run the majority of the new test suites. I think the only new one it runs is `PlayBuildAll`: https://github.com/xamarin/GooglePlayServicesComponents/pull/639/files#diff-91fcb59c3dd53babb75b34f23269bb6972fae348be4ade7f9e1786d4cafae586.
> 
> None of the other suites are added to `BuildAll.sln` or `build.cake`, so they are not being run by CI.

Yes. I fixed `build.cake`. Now it should be OK.

> `dotnet/BuildAllXamarinForms` is probably also unneeded, as XF does not run on .NET 6+.

iOS does not run, but Android does. It is "android only" XF project with XF references. The same like in AX.

**Comment by jpobst** [comment]
LGTM, I can't approve it because I'm the PR author.

**Comment by moljac** [comment]
> LGTM, I can't approve it because I'm the PR author.

fixing conflict and will merge

**Pull request merged**
