### PR TITLE
Legacy branch/PR 71.x.y.z-legacy-Android.Support - DO NOT MERGE to ma…

### PR DESCRIPTION
**Pull request by moljac**
### Google Play Services Version (eg: 8.4.0):

71.x.y.z Android.Support -Legacy

### Does this change any of the generated binding API's?

Yes. Master is AndroidX based (1xx.y.z)

### CODE REVIEW

**Comment by mattleibow** [comment]
Do we need this PR for anything? If we are not going to merge it, what was the reason for this?

**Comment by moljac** [comment]
@mattleibow 
Yes we are going to merge it to master. I will remove label when everything is ready.

Is that OK with you?

**Comment by mattleibow** [comment]
Ah, I see. Makes sense.

Fingers crossed we never have to use it!

**Comment by jpobst** [comment]
I think we're past any threat of needing to service the Android Support versions now.  ;)

**Pull request closed without merging**
