### PR TITLE
Add `$schema` to `cgmanifest.json`

### PR DESCRIPTION
**Pull request by JamieMagee**
This pull request adds the JSON schema for `cgmanifest.json`.

### Why?

A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.

### How can I validate my `cgmanifest.json` file?

Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.

### Why does it suggest camel case for the properties?

Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.

### Why is the diff so large?

To deserialize the `cgmanifest.json` file, we use [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse).
However, to serialize the JSON again we use [`prettier`](https://prettier.io/).
We found that, in general, it gave smaller diffs than the default [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) function.

### CODE REVIEW

**Comment by moljac** [comment]
Please. Request for review when it PR is ready.

Thanks

**Comment by JamieMagee** [comment]
@moljac I'm unable to request for review through the GitHub UI as I'm not a member of the xamarin organization or this repository. Regardless, the PR is ready for review now.

**Comment by moljac** [comment]
> @moljac I'm unable to request for review through the GitHub UI as I'm not a member of the xamarin organization or this repository. Regardless, the PR is ready for review now.

Shouldn't community members (not being part of Xamarin or any org) be able to raise PR?

Never mind.

Since we generate those files automagically I need to update some serialization code. As soon as I fix that, bump the nuget package[s] i will merge scripts and these PRs. I hope this is OK.

**Comment by JamieMagee** [comment]
That sounds great, thank you. I'll leave it with you.

**Comment by moljac** [comment]
here is the PR with automagically generated `cgmanifest.json`

https://github.com/xamarin/GooglePlayServicesComponents/pull/683

I hope this is better.

**Comment by moljac** [comment]
Automatically generated `cgmanifest.json` is fixed

- schema was added
- property names use camelCase

https://github.com/xamarin/GooglePlayServicesComponents/blob/main/cgmanifest.json

closing this one without merging.

Thanks

**Pull request closed without merging**
