### PR TITLE
Template set bumptech glide

### PR DESCRIPTION
**Pull request by moljac**
### Describe your contribution

1. Moved `Xamarin.Android.Glide.*` to this repo from:
   https://github.com/xamarin/XamarinComponents/tree/main/Android/Glide 
2. created template set

### Does this change any of the generated binding API's?

No. TFM was added eariler.

### Artifacts updated

- com.github.bumptech.glide:glide -  -> 4.11.0

  - [diff.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/7362833/Xamarin.Android.Glide.dll.diff.md.txt)

  - [breaking.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/7362832/Xamarin.Android.Glide.dll.breaking.md.txt)

- com.github.bumptech.glide:annotations -  -> 4.11.0

  - [diff.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/7362843/Xamarin.Android.Glide.Annotations.dll.diff.md.txt)

  - [breaking.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/7362842/Xamarin.Android.Glide.Annotations.dll.breaking.md.txt)

- com.github.bumptech.glide:gifdecoder -  -> 4.11.0

  - no API changes

- com.github.bumptech.glide:disklrucache -  -> 4.11.0

  - no API changes

- com.github.bumptech.glide:recyclerview-integration -  -> 4.11.0

  - [diff.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/7362851/Xamarin.Android.Glide.RecyclerViewIntegration.dll.diff.md.txt)

  - [breaking.md.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/7362850/Xamarin.Android.Glide.RecyclerViewIntegration.dll.breaking.md.txt)

## Dependencies

- androidx.vectordrawable:vectordrawable-animated -  -> 1.1.0

Checklist
- [x] Add any metadata needed to get PR to compile
- [x] Verify any new namespaces are properly renamed (utilities.cake)
- [x] Verify nuget/namespace spelling (utilities.cake)           
- [x] Locally generate diffs
- [x] Review any breaking changes
- [x] Attach diffs to PR

### CODE REVIEW

**Comment by jpobst** [comment]
XamarinComponents is "community-maintained" which in effect is "rarely maintained".  These dependencies need to be maintained by Microsoft like AndroidX/GPS.  

By moving our AndroidX/GPS dependencies into their respective repos they can participate in our automated infrastructure to keep them updated:
- A GitHub action automatically scans Maven every week and opens a PR for updates it finds
- Standardizing on `binderator` makes updates easier
- Dependencies between NuGets are automatically updated if the POM changes, which is rarely noticed when doing it manually

**Comment by jonathanpeppers** [comment]
Yeah, I just thought the commit message should say why we're moving it.

Let me know if you need help figuring out what is missing in the `.nupkg`, thanks.

**Comment by moljac** [comment]
### Content comparison:

Old orginal nuget:

```
tree -h xamarin.android.glide.4.12.0.2/ 
```

output:

```
xamarin.android.glide.4.12.0.2/
├── [5.3K]  THIRD-PARTY-NOTICES.txt
├── [3.4K]  Xamarin.Android.Glide.nuspec
├── [ 721]  [Content_Types].xml
├── [  96]  _rels
├── [  96]  aar
│   └── [625K]  glide.aar
├── [ 160]  build
│   ├── [  96]  monoandroid10.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   ├── [  96]  monoandroid9.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   └── [  96]  net6.0-android31.0
│       └── [ 235]  Xamarin.Android.Glide.targets
├── [ 160]  buildTransitive
│   ├── [  96]  monoandroid10.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   ├── [  96]  monoandroid9.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   └── [  96]  net6.0-android31.0
│       └── [ 235]  Xamarin.Android.Glide.targets
├── [ 160]  lib
│   ├── [ 128]  monoandroid10.0
│   │   ├── [1.0M]  Xamarin.Android.Glide.dll
│   │   └── [ 146]  Xamarin.Android.Glide.xml
│   ├── [ 128]  monoandroid90
│   │   ├── [1.0M]  Xamarin.Android.Glide.dll
│   │   └── [ 146]  Xamarin.Android.Glide.xml
│   └── [ 128]  net6.0-android31.0
│       ├── [1.0M]  Xamarin.Android.Glide.dll
│       └── [ 146]  Xamarin.Android.Glide.xml
└── [  96]  package
    └── [  96]  services
        └── [  96]  metadata
            └── [  96]  core-properties
                └── [ 683]  daf57c74cc4549d499b60a298d419e12.psmdcp

18 directories, 17 files
```

new nuget:

```bash
tree -h Xamarin.Android.Glide.4.12.0.3/                                
```

output:

```
tree -h Xamarin.Android.Glide.4.12.0.3/   
Xamarin.Android.Glide.4.12.0.3/
├── [1.1K]  LICENSE.md
├── [5.3K]  THIRD-PARTY-NOTICES.txt
├── [3.7K]  Xamarin.Android.Glide.nuspec
├── [ 783]  [Content_Types].xml
├── [  96]  _rels
├── [  96]  aar
│   └── [625K]  glide.aar
├── [ 160]  build
│   ├── [  96]  monoandroid10.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   ├── [  96]  monoandroid9.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   └── [  96]  net6.0-android31.0
│       └── [ 235]  Xamarin.Android.Glide.targets
├── [ 160]  buildTransitive
│   ├── [  96]  monoandroid10.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   ├── [  96]  monoandroid9.0
│   │   └── [ 235]  Xamarin.Android.Glide.targets
│   └── [  96]  net6.0-android31.0
│       └── [ 235]  Xamarin.Android.Glide.targets
├── [ 160]  lib
│   ├── [ 128]  monoandroid10.0
│   │   ├── [1.0M]  Xamarin.Android.Glide.dll
│   │   └── [ 146]  Xamarin.Android.Glide.xml
│   ├── [ 128]  monoandroid90
│   │   ├── [1.0M]  Xamarin.Android.Glide.dll
│   │   └── [ 146]  Xamarin.Android.Glide.xml
│   └── [ 128]  net6.0-android31.0
│       ├── [1.0M]  Xamarin.Android.Glide.dll
│       └── [ 146]  Xamarin.Android.Glide.xml
└── [  96]  package
    └── [  96]  services
        └── [  96]  metadata
            └── [  96]  core-properties
                └── [ 688]  42e6182f27614347b013dde021ce9c96.psmdcp

18 directories, 18 files
```

**Review by jonathanpeppers — APPROVED** [review]
The `.nupkg` looks correct now, thanks! 👍

**Pull request merged**
