### PR TITLE
GPS/FB September 2020 Updates

### PR DESCRIPTION
**Pull request by jpobst**
## Google Play Services
- com.google.android.gms.play-services-ads (19.3.0 -> 19.4.0)
  - No public API changes
- com.google.android.gms.play-services-ads-base (19.3.0 -> 19.4.0)
  - No public API changes
- com.google.android.gms.play-services-ads-lite (19.3.0 -> 19.4.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5698829/Xamarin.GooglePlayServices.Ads.Lite.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5698830/Xamarin.GooglePlayServices.Ads.Lite.dll.diff.txt)
- com.google.android.gms.play-services-cloud-messaging (16.0.0)
  - New binding
- com.google.android.gms.play-services-gass (19.3.0 -> 19.4.0)
  - No public API changes
- com.google.android.gms.play-services-location (17.0.0 -> 17.1.0)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691729/Xamarin.GooglePlayServices.Location.dll.diff.txt)

## Firebase
- com.google.firebase.firebase-ads (19.3.0 -> 19.4.0)
  - No public API changes
- com.google.firebase.firebase-ads-lite (19.3.0 -> 19.4.0)
  - No public API changes
- com.google.firebase.firebase-auth (19.3.2 -> 19.4.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691735/Xamarin.Firebase.Auth.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691737/Xamarin.Firebase.Auth.dll.diff.txt)
- com.google.firebase.firebase-crashlytics (17.2.1 -> 17.2.2)
  - No public API changes
- com.google.firebase.firebase-crashlytics-ndk (17.2.1 -> 17.2.2)
  - No public API changes
- com.google.firebase.firebase-database (19.4.0 -> 19.5.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691745/Xamarin.Firebase.Database.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691746/Xamarin.Firebase.Database.dll.diff.txt)
- com.google.firebase.firebase-encoders (16.0.0)
  - New binding
- com.google.firebase.firebase-encoders-json (16.1.0 -> 17.0.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691749/Xamarin.Firebase.Encoders.JSON.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691750/Xamarin.Firebase.Encoders.JSON.dll.diff.txt)
- com.google.firebase.firebase-firestore (21.6.0 -> 21.7.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691753/Xamarin.Firebase.Firestore.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691754/Xamarin.Firebase.Firestore.dll.diff.txt)
- com.google.firebase.firebase-iid (20.2.4 -> 20.3.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691757/Xamarin.Firebase.Iid.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691758/Xamarin.Firebase.Iid.dll.diff.txt)
- com.google.firebase.firebase-messaging (20.2.4 -> 20.3.0)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691767/Xamarin.Firebase.Messaging.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5691768/Xamarin.Firebase.Messaging.dll.diff.txt)
- com.google.firebase.firebase-perf (19.0.8 -> 19.0.9)
  - [breaking.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5698833/Xamarin.Firebase.Perf.dll.breaking.txt)
  - [diff.txt](https://github.com/xamarin/GooglePlayServicesComponents/files/5698834/Xamarin.Firebase.Perf.dll.diff.txt)

### CODE REVIEW

**Comment by moljac** [comment]
Found

### com.google.android.gms.play-services-ads-lite (19.3.0 -> 19.4.0)

```
### Namespace Com.Google.Android.Gms.Ads.Rewardedinterstitial
```

metadata for package might be missing


### Firebase.Iid.FirebaseInstanceIdReceiver

Modified base type:

```diff
-AndroidX.Legacy.Content.WakefulBroadcastReceiver
+Android.Gms.CloudMessaging.CloudMessagingReceiver
```

*code smell... Back to legacy?*

### com.google.firebase.firebase-perf (19.0.8 -> 19.0.9

```
### New Namespace Com.Google.Firebase.Perf.Gauges
### New Namespace Com.Google.Firebase.Perf.Impl
### New Namespace Com.Google.Firebase.Perf.Logging
### New Namespace Com.Google.Firebase.Perf.Util
### New Namespace Com.Google.Firebase.Perf.V1
```

I guess again metadata for namespaces is needed!

**Comment by moljac** [comment]
I usually do when everything builds:

```
find ./generated -type f -name "Com.*.cs"
```

And have started APiXmlSpitter tool that grabs `package` node from `api.xml` and generates that metadata...
Next step for improvements...



]

**Review by moljac — CHANGES_REQUESTED** [review]
LGTM except namespaces and one type change.

See comment on PR please

**Comment by jpobst** [comment]
Good catches!

Fixed the namespaces.

It looks like `Android.Gms.CloudMessaging.CloudMessagingReceiver` is a type in the new `com.google.android.gms.play-services-cloud-messaging` package this PR binds, so it's not from Android legacy.

**Comment by moljac** [comment]
Yes. Google does cr4p like that. I wanted just to check/verify - to be sure.

**Review by moljac — APPROVED** [review]
LGTM

**Pull request merged**
