### PR TITLE
Import `Xamarin.Android.Google.BillingClient*` packages from XamarinComponents.

### PR DESCRIPTION
**Pull request by jpobst**
Import Xamarin.Android.Google.BillingClient* packages from XamarinComponents so they will be supported.

### Xamarin.Android.Google.BillingClient:
image

Note this now uses the GooglePlayServices template, which is correct, as this package is licensed under the Android SDK License, it is not Apache, and thus we should not be including the `.aar` in the NuGet like we previously were.

Note also that we are _still_ including the `.aar` in the NuGet, which is incorrect, however this is a bug in our GPS template which is currently doing this for all packages and needs to be fixed separately.

### Xamarin.Android.Google.BillingClient.Ktx:

image

Same notes apply for this package.

### CODE REVIEW

**Review by moljac — APPROVED** [review]

**Comment by moljac** [comment]
I think SignList.xml should be added too.

**Comment by moljac** [comment]
Q: How/when do you decide to do "template sets"?

just curious.

**Comment by jpobst** [comment]
Is there any reason not to add `Xamarin.*` to the `SignList.xml` like XC does?
https://github.com/xamarin/XamarinComponents/blob/main/SignList.xml#L4-L7

I think it's pretty safe to say that we want everything that starts with `Xamarin` to be signed.

**Comment by jpobst** [comment]
> Q: How/when do you decide to do "template sets"?

Ideally, I think we want as few templates as possible.  The majority of the content in them is duplicated and it means we have to update many places when we want to make changes (ie: https://github.com/xamarin/AndroidX/pull/629).

Eventually I plan on working to reduce the number of templates we have by making the default template more flexible, but it's not a priority.  

For `BillingClient` it was similar enough to the rest of GPS to use the template.  Also the XC version did not use XBD which is required since `BillingClient` is Android SDK licensed, so that had to change anyways.

**Comment by vecalion** [comment]
@jpobst @moljac I created a PR updating the billingclient to 5.0.0. 
https://github.com/xamarin/XamarinComponents/pull/1416
Should I get it here or will you take care of updating the lib?

**Comment by moljac** [comment]
@vecalion Thanks a lot. I will check it, but Biling client is now in GPS-FB-MLKit repo and we'll take care of updates.

> @jpobst @moljac I created a PR updating the billingclient to 5.0.0. [xamarin/XamarinComponents#1416](https://github.com/xamarin/XamarinComponents/pull/1416) Should I get it here or will you take care of updating the lib?

No. It is OK. I will take care. Just to solve few issues I have. Updates will now be automagic in sync with GPS-FB-MLKit packages - twice per month.

**Pull request merged**
