### PR TITLE
Manual updates 20221024 tf lite only

### PR DESCRIPTION
**Pull request by moljac**
### Does this change any of the generated binding API's?

Yes (new and updated APIs)

### Describe your contribution

bindings for some updates and new packages (dependencies):

- `com.google.flatbuffers:flatbuffers-java` -  -> 1.12.0
- `org.tensorflow:tensorflow-lite-select-tf-ops` -  -> 2.10.0
- `org.tensorflow:tensorflow-android` -  -> 1.13.1
- `org.tensorflow:tensorflow-lite-support` -  -> 0.4.2
- `org.tensorflow:tensorflow-lite-metadata` -  -> 0.4.2
- `org.tensorflow:tensorflow-lite-task-base` -  -> 0.4.2

### CODE REVIEW

**Comment by moljac** [comment]
related 

https://github.com/xamarin/GooglePlayServicesComponents/issues/667

**Comment by moljac** [comment]
local build error on Mac

```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.476/tools/Xamarin.Android.Bindings.ClassParse.targets(30,5): 
error MSB6006: "dotnet" exited with code 134. [/../generated/com.google.firebase.firebase-perf-ktx/com.google.firebase.firebase-perf-ktx.csproj]
```

**Comment by moljac** [comment]
> local build error on Mac
> 
> build:
> 
> ```
> dotnet build \
>     generated/com.google.firebase.firebase-perf-ktx/com.google.firebase.firebase-perf-ktx.csproj
> ```
> 
> error:
> 
> ```
> /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets(30,5): 
> error MSB6006: "mono" exited with code 1. 
> [./generated/com.google.firebase.firebase-perf-ktx/com.google.firebase.firebase-perf-ktx.csproj]
> 
> /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.476/tools/Xamarin.Android.Bindings.ClassParse.targets(30,5): 
> error MSB6006: "dotnet" exited with code 134. 
> [./generated/com.google.firebase.firebase-perf-ktx/com.google.firebase.firebase-perf-ktx.csproj]
> ```

workaround was to bump versions in `global.json`

Cause? Not sure. There was OS update (upgraded to Ventura forced by InTune), .NET updates + VS4Mac updates.

**Review by jpobst — COMMENTED** [review]
It looks like commit https://github.com/xamarin/GooglePlayServicesComponents/commit/4ef522de9cc898a054e4cf417348ca74fa4a4e40 has broken parameter names for 30-40 bindings in this repository.  We will not be able to commit and publish new packages from this repo until it is fixed properly.

**Comment by moljac** [comment]
> It looks like commit [4ef522d](https://github.com/xamarin/GooglePlayServicesComponents/commit/4ef522de9cc898a054e4cf417348ca74fa4a4e40) has broken parameter names for 30-40 bindings in this repository. We will not be able to commit and publish new packages from this repo until it is fixed properly.

I have the files, but where to host them?

**Comment by jpobst** [comment]
How big are the file(s)? We might could keep them in this repository.

**Comment by moljac** [comment]
> How big are the file(s)? We might could keep them in this repository.

This is what I would do in my projects.

original names (`build .cake` script renames files):

```
-rw-r--r--  1 moljac  wheel    59M Jul  7 01:58 ./externals/docs.zip
-rw-r--r--  1 moljac  wheel   1.9M Jul  7 01:59 ./externals/paramnames.xml
-rw-r--r--  1 moljac  wheel   351K Jul  7 01:59 ./externals/paramnames.txt
```

I have saved with original names:

```
-rw-r--r--  1 moljac  wheel    59M Jul  7 01:58 ./data/docs/play-services-firebase.zip
-rw-r--r--  1 moljac  wheel   1.9M Jul  7 01:59 ./data/paramnames/play-services-firebase-metadata.xml
-rw-r--r--  1 moljac  wheel   351K Jul  7 01:59 ./data/paramnames/play-services-firebase-paramnames.txt
```

**Review by jpobst — APPROVED** [review]

**Pull request merged**
