### PR TITLE
Manual updates 20220215 (after 3 months)

### PR DESCRIPTION
**Pull request by moljac**
PR split into:

* https://github.com/xamarin/GooglePlayServicesComponents/pull/605
* https://github.com/xamarin/GooglePlayServicesComponents/pull/606
* https://github.com/xamarin/GooglePlayServicesComponents/pull/607
* https://github.com/xamarin/GooglePlayServicesComponents/pull/608

### Does this change any of the generated binding API's?

Most likely due to

- updates
- new packages

### Describe your contribution
- updated packages
  - updated `com.google.android.gms:play-services-ads`
    - https://github.com/xamarin/GooglePlayServicesComponents/issues/584
- added `com.google.android.gms:play-services-appset`
  - https://github.com/xamarin/GooglePlayServicesComponents/issues/587
- added `com.google.zxing:core`
  - https://github.com/xamarin/GooglePlayServicesComponents/issues/581
  
### Fixes for

*   publishing would unblock AX PRs (dependencies new and updated)

    *   https://github.com/xamarin/AndroidX/pull/468 

*   Xamarin.Firebase.Messaging crashing on failed resolution of datatransport/TransportFactory

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/604

    `Xamarin.Google.Android.DataTransport.TransportRuntime` 
    `Xamarin.Google.Android.DataTransport.TransportBackendCct`
    3.1.2 missing

*   https://github.com/xamarin/GooglePlayServicesComponents/issues/603

    `Xamarin.Google.UserMessagingPlatform`
    2.0.0 missing

*   Xamarin.GooglePlayServices.Ads.Lite needs newer Xamarin.AndroidX.Work.Runtime dependency

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/592

*   Add Google Play Services Appset binding

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/587

*   update Google Mobile Ads-SDK to 20.4.0 needed

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/584

*   Google Cast failed on Android 12 - Missing Flag_Immutable

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/576

*   Xamarin.GooglePlayServices.Maps with .Net 6

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/577

*   Add bindings for Maps v18

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/562

*   Failed resolution of: Lcom/google/android/datatransport/TransportFactory when using Xamarin.Firebase in MAUI

    *   https://github.com/xamarin/GooglePlayServicesComponents/issues/560  

*   Are Google Maps supported yet? (MAUI Facebook group)

    *   https://www.facebook.com/groups/dotnetmaui/permalink/967146800651683/

### CODE REVIEW

**Comment by jpobst** [comment]
The current CI error is:
```
Xamarin.Firebase.Measurement.Connector.Impl depends on Xamarin.GooglePlayServices.Measurement.Api (>= 117.0.5.4) but Xamarin.GooglePlayServices.Measurement.Api 117.0.5.4 was not found. An approximate best match of Xamarin.GooglePlayServices.Measurement.Api 117.2.2 was resolved.
```

This is likely because we have both of these entries:
```
{
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-api",
        "version": "19.0.2",
        "nugetVersion": "119.0.2",
        "nugetId": "Xamarin.GooglePlayServices.Measurement.Api",
        "dependencyOnly": false
},
{
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-api",
        "version": "16.3.0",
        "nugetVersion": "117.0.5.4",
        "nugetId": "Xamarin.GooglePlayServices.Measurement.Api",
        "dependencyOnly": true
}
```

This will cause some projects to take a `<ProjectReference>` on the `119.0.2` version while other projects take a `<PackageReference>` to the `117.0.5.4` version.

Each artifact should only be specified once so that everything uses the same version, preventing conflicts.

**Comment by moljac** [comment]
> The current CI error is:
> 
> ```
> Xamarin.Firebase.Measurement.Connector.Impl depends on Xamarin.GooglePlayServices.Measurement.Api (>= 117.0.5.4) but Xamarin.GooglePlayServices.Measurement.Api 117.0.5.4 was not found. An approximate best match of Xamarin.GooglePlayServices.Measurement.Api 117.2.2 was resolved.
> ```
> 
> This is likely because we have both of these entries:
> 
> ```
> {
>         "groupId": "com.google.android.gms",
>         "artifactId": "play-services-measurement-api",
>         "version": "19.0.2",
>         "nugetVersion": "119.0.2",
>         "nugetId": "Xamarin.GooglePlayServices.Measurement.Api",
>         "dependencyOnly": false
> },
> {
>         "groupId": "com.google.android.gms",
>         "artifactId": "play-services-measurement-api",
>         "version": "16.3.0",
>         "nugetVersion": "117.0.5.4",
>         "nugetId": "Xamarin.GooglePlayServices.Measurement.Api",
>         "dependencyOnly": true
> }
> ```
> 
> This will cause some projects to take a `<ProjectReference>` on the `119.0.2` version while other projects take a `<PackageReference>` to the `117.0.5.4` version.
> 
> Each artifact should only be specified once so that everything uses the same version, preventing conflicts.

good spot... but, IIRC 1st one is new to bind and 2nd one is dependency of some package I had to add to make binderator happy.

I will try not to bump/update the 1st one. That might unblock the rest

Wild guess only

**Comment by moljac** [comment]
Entry 


was dangerous trick

Removing:

```
      {
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-api",
        "version": "16.3.0",
        "nugetVersion": "116.3.0",
        "nugetId": "Xamarin.GooglePlayServices.Measurement.Api",
        "dependencyOnly": true
      },
```

leads to binderator errors:

```
Dependency errors : 4
1
	System.Exception: 
No matching artifact config found for: 
			com.google.android.gms.play-services-measurement-base:[19.0.1]
to satisfy dependency of: 
			com.google.android.gms.play-services-measurement-api:19.0.1

	Please add following json snippet to config.json:


      {
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-base",
        "version": "[19.0.1]",
        "nugetVersion": "CHECK PREFIX [19.0.1]",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }
						


2
	System.Exception: 
No matching artifact config found for: 
			com.google.android.gms.play-services-measurement-sdk-api:[19.0.1]
to satisfy dependency of: 
			com.google.android.gms.play-services-measurement-api:19.0.1

	Please add following json snippet to config.json:


      {
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-sdk-api",
        "version": "[19.0.1]",
        "nugetVersion": "CHECK PREFIX [19.0.1]",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }
						


3
	System.Exception: 
No matching artifact config found for: 
			com.google.android.gms.play-services-measurement-api:19.0.2
to satisfy dependency of: 
			com.google.firebase.firebase-analytics:19.0.2

	Please add following json snippet to config.json:


      {
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-api",
        "version": "19.0.2",
        "nugetVersion": "CHECK PREFIX 19.0.2",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }
						


4
	System.Exception: 
No matching artifact config found for: 
			com.google.android.gms.play-services-measurement-api:[16.3.0]
to satisfy dependency of: 
			com.google.firebase.firebase-measurement-connector-impl:17.0.5

	Please add following json snippet to config.json:


      {
        "groupId": "com.google.android.gms",
        "artifactId": "play-services-measurement-api",
        "version": "[16.3.0]",
        "nugetVersion": "CHECK PREFIX [16.3.0]",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }
```

The problem is requirement for exact version [16.3.0] which was not published as nuget.

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Measurement.Api/

**Comment by jpobst** [comment]
It feels like this has gotten so far out of date that doing it all as one gigantic PR isn't going to be feasible.  Let's try to break this up into smaller more manageable chunks.

I would suggest we start at the bottom of the dependency tree, get those updates merged, and then move up the tree.

That is, we work through this list as separate PRs:
- Dependencies (glide/square/grpc/etc)
- GPS (minus MLKit stuff like `play-services-mlkit`)
- Firebase
- MLKit

If we need to update everything to `MonoAndroid12.0` first due to AndroidX dependencies, let's do that first in a separate PR and get it merged.

**Comment by moljac** [comment]
> It feels like this has gotten so far out of date that doing it all as one gigantic PR isn't going to be feasible. 

7 months. Postponing will only make it worse.

> Let's try to break this up into smaller more manageable chunks.

I'm not sure this will be easy task:

see:

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Measurement.Api/

GPS depending on FB. 


And since begin of 2022 we have AndroidX depending on FB:

https://github.com/xamarin/AndroidX/blob/mu-20220124/config.json#L1817-L1840

https://github.com/xamarin/AndroidX/pull/468


> I would suggest we start at the bottom of the dependency tree, get those updates merged, and then move up the tree.
> 
> That is, we work through this list as separate PRs:
> 
> * Dependencies (glide/square/grpc/etc)
> * GPS (minus MLKit stuff like `play-services-mlkit`)
> * Firebase
> * MLKit
> 
> If we need to update everything to `MonoAndroid12.0` first due to AndroidX dependencies, let's do that first in a separate PR and get it merged.

`main` is on `MonoAndroid12.0` and this PR was created 2 months ago, about the time when we switched AndroidX to `MonoAndroid12.0`, so it was added later.

https://github.com/xamarin/GooglePlayServicesComponents/blob/mu-20220215/source/GooglePlayServicesProject.cshtml#L6-L7

IMO *hopefully* feasible PRs will be:

1. dependencies and `MonoAndroid12.0`
2. GPS-FB
3. MLKit

feasible in a sense that it will not take weeks to approve, merge and publish.

And skipping versions should not be done. I am willing to do manual updates until we catch up with current status. From my experience skipping minor version could lead to acceptable cadence and results.

**Comment by moljac** [comment]
More fun:

updating dependencies only:

```json
Dependency errors : 1
1
	System.Exception: 
No matching artifact config found for: 
			com.google.firebase.firebase-encoders-proto:16.0.0
to satisfy dependency of: 
			com.google.android.datatransport.transport-runtime:3.1.3

	Please add following json snippet to config.json:


      {
        "groupId": "com.google.firebase",
        "artifactId": "firebase-encoders-proto",
        "version": "16.0.0",
        "nugetVersion": "CHECK PREFIX 16.0.0",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }						
```

it boils down almost to do `config.json` update per artifact.

**Pull request closed without merging**
