### PR TITLE
Androidx 201908

### PR DESCRIPTION
**Pull request by moljac**
### Google Play Services Version (eg: 8.4.0):

Google.Play.Services and Firebase with AndroidX dependencies.

### Does this change any of the generated binding API's?

Yes

### Describe your contribution

Binderator confiog and bindings.

### CODE REVIEW

**Comment by Dona278** [comment]
Hello! Is there a release date for NuGet packages? I'm working on a new app and it would be perfect to start with AndroidX..

**Comment by moljac** [comment]
@Dona278 
Not yet. You must build it yourself right now. But very close.

**Comment by RedChops** [comment]
I've bumped a ton of the Firebase libraries in my own fork to their somewhat latest version as far as I can. Some of the latest versions require libraries outside the scope of this project so I left them alone.

Would you be interested in a PR for this, or should I hold off until after release?

**Comment by moljac** [comment]
@RedChops 

Thanks for the offer. I have bumped in Feb (202002 branch), but those external dependencies and AndroidX are blocking me for now.
Besides external dependencies go to XamarinComponents repo... Process is a bit complex, but we must obey.

**Comment by VladislavAntonyuk** [comment]
are there any plans when it will be merged?

**Comment by moljac** [comment]
@VladislavAntonyuk 

Why do you want to merge? To master? I think you would like stable release packages and those can be published from the branch.

`master` is 71.xxx

`master_based_androidx_BLAH_BLAH` are 100.xxx versions (AndroidX) branches and I am publishing previews now to get first feedback and fix issues as they appear.

No need to merge right now, but eventually -  for sure.

**Comment by VladislavAntonyuk** [comment]
> @VladislavAntonyuk
> 
> Why do you want to merge? To master? I think you would like stable release packages and those can be published from the branch.
> 
> `master` is 71.xxx
> 
> `master_based_androidx_BLAH_BLAH` are 100.xxx versions (AndroidX) branches and I am publishing previews now to get first feedback and fix issues as they appear.
> 
> No need to merge right now, but eventually - for sure.

Thank you for the feedback. I didn't include pre-release packages, that is why I didn't see 100.xxx versions. Also created a defect: https://github.com/xamarin/GooglePlayServicesComponents/issues/347

**Comment by moljac** [comment]
@VladislavAntonyuk 
I am performing numerous tests with AndroidX. Namely we have a lot of new MsBuild tasks for the future (.NET5 and .NET6). This is the main reason for not publishing release[s]. I hope soon. Few days. I'm cleaning up some easier issues and then I'll publish releases.

Regarding issue #347 - most likely R8 which is default now. It is more aggressive than proguard, so I would try with proguard rules 1st. I'm quite sure that is an issue.

And please report there (and here if you have time) if that helped. Of course you could close the issue if it works.

**Comment by VladislavAntonyuk** [comment]
https://github.com/xamarin/GooglePlayServicesComponents/issues/347#issuecomment-643955789

**Comment by RedChops** [comment]
I'm just getting back to this project of mine, updated to these new published previews. It seems that at least Firestore has a possibly hard dependency on Guava 23. When I tried to run my app with Guava 28.2.0, it crashed with a class-not-found for `com.google.common.io.BaseEncoding`. Downgrading back to 23 fixes it

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
